#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# PyAbel documentation build configuration file, created by
# sphinx-quickstart on Wed Jan 13 17:11:12 2016.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import six
import os
import shlex

import sphinx_rtd_theme

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath('../'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.mathjax',
    'sphinx.ext.napoleon',
    'sphinx.ext.viewcode',
    'matplotlib.sphinxext.plot_directive'
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
#source_suffix = {'.rst': 'restructuredtext'}

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'PyAbel'
copyright = u'2016–2024, PyAbel team'
author = 'PyAbel team'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
import abel
# The short X.Y version.
version = abel._version.__version__
# The full version, including alpha/beta/rc tags.
release = version

# Generate/update the DOI file.
exec(open('conf/doi.py').read())

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The reST default role (used for this markup: `text`) to use for all
# documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
#keep_warnings = False

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# Properly format combined parameters with common type/description.
napoleon_use_param = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
#html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#html_logo = None

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['static']

html_css_files = ['custom.css']

html_js_files = []  # MathJax might be added here below

# Try to download MathJax for HTML.
exec(open('conf/mathjax.py').read())

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
#html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'h', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'r', 'sv', 'tr'
#html_search_language = 'en'

# A dictionary with options for the search language support, empty by default.
# Now only 'ja' uses this config value
#html_search_options = {'type': 'default'}

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
#html_search_scorer = 'scorer.js'

# Output file base name for HTML help builder.
htmlhelp_basename = 'PyAbeldoc'

# Options for matplotlib.sphinxext.plot_directive.
# use SVG by default, make PDF for pdfLaTeX
plot_formats = ['svg', 'png', 'pdf']
# do not add links to source automatically
plot_html_show_source_link = False
# do not add links to image formats
plot_html_show_formats = False


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #'pointsize': '10pt',

    # Extra options for documentclass
    'extraclassoptions': 'openany',  # allow chapter to start on even pages

    # Disable "fancy" chapter formatting
    'fncychap': '',

    # Additional options for packages
    'passoptionstopackages': r'\PassOptionsToPackage{table}{xcolor}',

    # Additional stuff for the LaTeX preamble.
    'preamble':
        r'''
        % additional Unicode characters:
        \DeclareUnicodeCharacter{03B2}{\ensuremath{\beta}} % β
        \DeclareUnicodeCharacter{03B8}{\ensuremath{\theta}} % θ
        \DeclareUnicodeCharacter{03C0}{\ensuremath{\pi}} % π
        \DeclareUnicodeCharacter{202F}{\,} % narrow nbsp
        \DeclareUnicodeCharacter{2212}{\ensuremath{-}} % −
        \DeclareUnicodeCharacter{2225}{\ensuremath{\parallel}} % ∥
        \DeclareUnicodeCharacter{2248}{\ensuremath{\approx}} % ≈
        \DeclareUnicodeCharacter{2260}{\ensuremath{\ne}} % ≠
        \DeclareUnicodeCharacter{2264}{\ensuremath{\le}} % ≤
        \DeclareUnicodeCharacter{2265}{\ensuremath{\ge}} % ≥
        \DeclareUnicodeCharacter{226A}{\ensuremath{\ll}} % ≪
        \DeclareUnicodeCharacter{226B}{\ensuremath{\gg}} % ≫
        \DeclareUnicodeCharacter{2272}{\ensuremath{\lesssim}} % ≲
        \DeclareUnicodeCharacter{2273}{\ensuremath{\gtrsim}} % ≳
        \DeclareUnicodeCharacter{22C5}{\ensuremath{\cdot}} % ⋅
        \DeclareUnicodeCharacter{25BE}{\ensuremath{\blacktriangledown}} % ▾
        \DeclareUnicodeCharacter{27C2}{\ensuremath{\perp}} % ⟂
        \DeclareUnicodeCharacter{2A7D}{\ensuremath{\leqslant}} % ⩽
        \DeclareUnicodeCharacter{2A7E}{\ensuremath{\geqslant}} % ⩾
        % allow line break after underscore (some code doesn't fit otherwise)
        \renewcommand\_{\textunderscore\allowbreak}
        % table styling:
            % light gray background for headers
            \protected\def\sphinxstyletheadfamily{\cellcolor{black!10}}
            % remove all lines (TODO: how to keep top and bottom?)
            \setlength{\arrayrulewidth}{0pt}
            % increase row separation
            \def\arraystretch{1.5}
        % override hyphenation
        \hyphenation{BASEX Py-Abel}
        ''',

    # LaTeX figure (float) alignment
    'figure_align': 'H',  # don't float images (most have no captions)
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'PyAbel.tex', 'PyAbel Documentation', 'PyAbel team', 'manual')
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False

# If true, show page references after internal links.
#latex_show_pagerefs = False

# If true, show URL addresses after external links.
#latex_show_urls = False

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
#latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'pyabel', 'PyAbel Documentation',
     [author], 1)
]

# If true, show URL addresses after external links.
#man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'PyAbel', 'PyAbel Documentation', author,
     'PyAbel', 'A Python package for forward and inverse Abel transforms.',
     'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
#texinfo_appendices = []

# If false, no module index is generated.
#texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#texinfo_no_detailmenu = False

required_symlinks = [
    ('examples', '../examples/')
]

autodoc_member_order = 'bysource'

numfig = True

# supress the "nonlocal image URI found" warnings
import sphinx.environment
from docutils.utils import get_source_line

#def _warn_node(self, msg, node):
#    if not msg.startswith('nonlocal image URI found:'):
#        self._warnfunc(msg, '%s:%s' % get_source_line(node))

#sphinx.environment.BuildEnvironment.warn_node = _warn_node


# -- Options for the linkcheck builder ------------------------------------

# as of Jun 2024, default is 'Mozilla/5.0', but some websites don't like it
# and forbid access; thus using UA from a recent Chromium browser
# (still doesn't work for Science and Wiley, but OK for the rest)
user_agent = 'Chromium/125.0.6422.60 Linux'

# also avoid multiple parallel requests
linkcheck_workers = 1  # default is 5

# and reduce time-outs
linkcheck_timeout = 10
linkcheck_rate_limit_timeout = 70.0  # default is 300 s = 5 min
